# Generated by Django 5.2.6 on 2025-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('date_formation', models.DateField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id_formateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_formateur', models.CharField(default='')),
                ('prenom_formateur', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=500)),
                ('date_formation', models.DateField(blank=True, null=True)),
                ('intervenant', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id_partner', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='')),
                ('Attribute', models.CharField(default='')),
            ],
        ),
    ]
