# Generated by Django 5.2.6 on 2025-09-29 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0001_initial'),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='id_membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formateur', to='membre.membre'),
        ),
        migrations.AddField(
            model_name='formation',
            name='id_formateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formation.formateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='id_membre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='membre.membre'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='formation.formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='id_partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formation.partner'),
        ),
    ]
