# Generated by Django 5.2.6 on 2025-09-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='duree_formation',
            field=models.PositiveIntegerField(blank=True, help_text='Durée de la formation en heures', null=True),
        ),
    ]
