# Generated by Django 5.2.6 on 2025-09-29 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id_badge', models.AutoField(primary_key=True, serialize=False)),
                ('qrcode', models.CharField(default='')),
                ('date_generation', models.DateField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReseauSociaux',
            fields=[
                ('id_reseau', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(default='')),
                ('nom_rs', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id_stack', models.AutoField(primary_key=True, serialize=False)),
                ('nom_stack', models.CharField(default='')),
                ('hard', models.CharField(default='')),
                ('soft', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Avertissement',
            fields=[
                ('id_avertissement', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_avertissement', models.IntegerField(default=0)),
                ('id_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membre.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_archive', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.CharField(default='')),
                ('date_archivage', models.DateField(default=False)),
                ('id_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='membre.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='')),
                ('prenom', models.CharField(default='')),
                ('image', models.FileField(default=None, upload_to='')),
                ('inscription_date', models.DateField(default=False)),
                ('badge_status', models.BooleanField(default=False)),
                ('address', models.CharField(default='')),
                ('phone_number', models.CharField(default='')),
                ('sexe', models.CharField(default='')),
                ('occupation', models.CharField(default='')),
                ('niveau_etude', models.CharField(default='')),
                ('ecole', models.CharField(default='')),
                ('role', models.CharField(default='')),
                ('id_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='membre.archive')),
                ('id_avertissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='membre.avertissement')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeFormation',
            fields=[
                ('id_dFormation', models.AutoField(primary_key=True, serialize=False)),
                ('nom_formation', models.CharField(default='')),
                ('description_formation', models.CharField(default='')),
                ('date_formation', models.DateField(default='')),
                ('duree_formation', models.CharField(default='')),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandeFormation', to='membre.membre')),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='id_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='membre.membre'),
        ),
        migrations.AddField(
            model_name='avertissement',
            name='id_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membre.membre'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id_presence', models.AutoField(primary_key=True, serialize=False)),
                ('presence', models.CharField(default='')),
                ('activite', models.CharField(default='')),
                ('date', models.DateField(default=False)),
                ('heure', models.CharField(default='')),
                ('id_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='formation.formation')),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='id_presence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='membre.presence'),
        ),
        migrations.AddField(
            model_name='membre',
            name='id_reseau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='membre.reseausociaux'),
        ),
        migrations.AddField(
            model_name='membre',
            name='id_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='membre.stack'),
        ),
        migrations.CreateModel(
            name='StatusCompte',
            fields=[
                ('id_statuscompte', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_comptes', to='membre.membre')),
            ],
        ),
    ]
