# Generated by Django 5.2.6 on 2025-10-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='motif',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='qrcode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='demandeformation',
            name='date_formation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandeformation',
            name='description_formation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='demandeformation',
            name='duree_formation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='demandeformation',
            name='id_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation', to='membre.membre'),
        ),
        migrations.AlterField(
            model_name='demandeformation',
            name='nom_formation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membre',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='membre',
            name='ecole',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='membre',
            name='inscription_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='niveau_etude',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='membre',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='membre',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='presence',
            name='activite',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='heure',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='presence',
            name='presence',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reseausociaux',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reseausociaux',
            name='nom_rs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stack',
            name='hard',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stack',
            name='nom_stack',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stack',
            name='soft',
            field=models.CharField(default='', max_length=255),
        ),
    ]
